fixtures:
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.22.0'
    apache:
      repo: 'https://github.com/puppetlabs/puppetlabs-apache.git'
      ref: '1.10.0'
    firewall:
      repo: 'https://github.com/puppetlabs/puppetlabs-firewall.git'
      ref: '1.8.1'
    concat:
      repo: 'https://github.com/puppetlabs/puppetlabs-concat.git'
      ref: '2.2.0'
    ip:
      repo: 'https://github.com/thrnio/puppet-ip.git'
      ref: 'v1.0.1'
  symlinks:
    yum: "#{source_dir}"
