---
appveyor.yml:
  delete: true

.gitlab-ci.yml:
  delete: true

.vscode/extensions.json:
  unmanaged: true

hiera.yaml:
  unmanaged: true

data/common.yaml:
  unmanaged: true

spec/spec_helper.rb:
  hiera_config: 'spec/fixtures/hiera/hiera.yaml'
